### ISSUE TITLE
interpretation of results

### ISSUE THREAD

**Issue by Hananebh** [holab-hku/DCATS#10]
hello,
Thank you again for the package, do you please have an example of interpretation of the results or example of plot to visualize the difference between the two conditions? please

Thank you

**Comment by linxy29** [comment]
I used the boxplot to show proportions and a significant bar to indicate the significant level as shown in Figure 4 here: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02980-3. You can find the related code at: https://github.com/linxy29/DCATS_anlysis/blob/master/figure4.Rmd.

**Comment by Hananebh** [comment]
Thank you very much
